# Generated by Django 5.2.16 on 2026-08-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0013_alter_pedido_courier_alter_skucourier_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespachoOnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(blank=True, choices=[('GUIA_PEDIDA', 'Guía pedida'), ('GUIA_LISTA', 'Guía lista'), ('ENTREGADO', 'Entregado')], max_length=20)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_compromiso_aproximada', models.BooleanField(default=False)),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('guia_despacho', models.CharField(blank=True, max_length=100)),
                ('observaciones_ok', models.TextField(blank=True)),
                ('confirmacion_cliente', models.BooleanField(default=False)),
                ('retorno_documento', models.BooleanField(default=False)),
                ('pedido_recibido', models.BooleanField(default=False)),
                ('observaciones_entrega', models.TextField(blank=True)),
                ('enviar', models.BooleanField(default=False)),
                ('confirmacion_carga', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_ont', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
