# Generated by Django 5.2.16 on 2026-09-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientoOnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachoont',
            name='accion',
            field=models.CharField(blank=True, choices=[('GUIA_LISTA', 'Guía lista'), ('GUIA_PEDIDA', 'Guía pedida'), ('PEDIR_GUIA', 'Pedir guía'), ('NO_ENVIAR_AUN', 'No enviar aún'), ('ENTREGADO', 'Entregado'), ('GARANTIA', 'Garantía')], max_length=20),
        ),
    ]
