# Generated by Django 5.2.16 on 2026-08-27 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP'), ('CYS', 'C&S'), ('BIOQUIMICACL', 'Bioquimica.cl'), ('STARKEN', 'Starken')], max_length=20)),
                ('orden_transporte', models.CharField(blank=True, max_length=100)),
                ('snapshot', models.JSONField()),
                ('pedidos_incluidos', models.JSONField(default=list)),
                ('motivo', models.TextField(blank=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
