# Generated by Django 5.2.16 on 2026-08-28 14:17

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviosIncidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioincidencia',
            name='snapshot',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
