# Generated by Django 5.2.16 on 2026-08-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecutivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecutivo',
            name='es_ont',
            field=models.BooleanField(default=False),
        ),
    ]
