# Generated by Django 5.2.16 on 2026-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=30)),
                ('orden_transporte', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
