# Generated by Django 5.2.16 on 2026-07-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocourier',
            name='datos_courier',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
