# Generated by Django 5.2.16 on 2026-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_enviocourier_datos_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviocourier',
            name='courier',
            field=models.CharField(choices=[('CHIBRA', 'Chibra')], max_length=20),
        ),
    ]
