# Generated by Django 5.2.16 on 2026-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_alter_enviocourier_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviocourier',
            name='courier',
            field=models.CharField(choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP')], max_length=20),
        ),
    ]
