# Generated by Django 5.2.16 on 2026-07-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_alter_enviocourier_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocourier',
            name='estado_courier',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='enviocourier',
            name='estado_courier_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
