# Generated by Django 5.2.16 on 2026-08-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_enviocourier_estado_courier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviocourier',
            name='courier',
            field=models.CharField(choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP'), ('CYS', 'C&S'), ('BIOQUIMICACL', 'Bioquimica.cl'), ('STARKEN', 'Starken')], max_length=20),
        ),
    ]
