# Generated by Django 5.2.16 on 2026-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0006_alter_enviocourier_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviocourier',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('ERROR', 'Error'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=30),
        ),
    ]
