# Generated by Django 5.2.16 on 2026-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0007_alter_enviocourier_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviocourier',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESPACHADO', 'Despachado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=30),
        ),
    ]
