# Generated by Django 5.2.16 on 2026-07-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejecutivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('SAP', 'SAP'), ('WEB', 'WEB')], max_length=20)),
                ('num_pedido', models.CharField(max_length=120, unique=True)),
                ('tipo_entrega', models.CharField(choices=[('RETIRO_EN_TIENDA', 'Retiro en tienda'), ('RETIRO_EN_BODEGA', 'Retiro en bodega'), ('DESPACHO', 'Despacho')], max_length=120)),
                ('transportation_code', models.IntegerField(blank=True, null=True)),
                ('u_bq_tipo_entrega', models.CharField(blank=True, max_length=120)),
                ('u_bq_crear_envio', models.CharField(blank=True, choices=[('Y', 'Si'), ('N', 'No')], max_length=10)),
                ('courier', models.CharField(blank=True, choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP')], max_length=20)),
                ('rut', models.CharField(max_length=120)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200)),
                ('telefono_contacto', models.CharField(blank=True, max_length=30)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('direccion_calle', models.CharField(blank=True, max_length=200)),
                ('direccion_depto', models.CharField(blank=True, max_length=20)),
                ('direccion_comuna', models.CharField(blank=True, max_length=100)),
                ('direccion_ciudad', models.CharField(blank=True, max_length=100)),
                ('estado_comercial', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=12)),
                ('estado_notificacion', models.CharField(choices=[('NO_NOTIFICADO', 'No notificado'), ('NOTIFICADO', 'Notificado')], default='NO_NOTIFICADO', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('orden_transporte', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('ejecutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejecutivos.ejecutivo')),
            ],
            options={
                'indexes': [models.Index(fields=['num_pedido'], name='pedidos_ped_num_ped_dea763_idx'), models.Index(fields=['ejecutivo'], name='pedidos_ped_ejecuti_675f3a_idx'), models.Index(fields=['estado_comercial'], name='pedidos_ped_estado__7a1ea3_idx'), models.Index(fields=['estado_notificacion'], name='pedidos_ped_estado__253b85_idx')],
            },
        ),
    ]
