# Generated by Django 5.2.16 on 2026-07-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='retirar_en',
            field=models.CharField(blank=True, choices=[('RETIRO_BODEGA_N3A', 'Retiro en Bodega (N3A)'), ('RETIRO_TIENDA_S2', 'Retiro en Tienda (S2)'), ('NO_APLICA', 'No aplica')], max_length=120),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('RETIRO_BIOQUIMICA', 'Retiro en Bioquimica'), ('DESPACHO', 'Despacho')], max_length=120),
        ),
    ]
