# Generated by Django 5.2.16 on 2026-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_retirar_en_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_depto',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
