# Generated by Django 5.2.16 on 2026-07-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecutivos', '0001_initial'),
        ('pedidos', '0003_alter_pedido_direccion_depto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='num_pedido',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('origen', 'num_pedido'), name='pedido_por_origen'),
        ),
    ]
