# Generated by Django 5.2.16 on 2026-07-20 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
        ('pedidos', '0004_alter_pedido_num_pedido_pedido_pedido_por_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='orden_transporte',
        ),
        migrations.AddField(
            model_name='pedido',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='envios.enviocourier'),
        ),
    ]
