# Generated by Django 5.2.16 on 2026-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_orden_transporte_pedido_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(choices=[('SGCHIBRA', 'Servicio de envío Chibra')], max_length=120, unique=True)),
                ('courier', models.CharField(choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP')], max_length=120)),
            ],
        ),
    ]
