# Generated by Django 5.2.16 on 2026-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_skucourier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skucourier',
            name='sku',
            field=models.CharField(choices=[('SGCHIBRA', 'sgchibra')], max_length=120, unique=True),
        ),
    ]
