# Generated by Django 5.2.16 on 2026-07-24 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_skucourier_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('NOTIFICADO', 'Notificado'), ('ANULADO', 'Anulado')], max_length=20)),
                ('origen', models.CharField(blank=True, max_length=20)),
                ('num_pedido', models.CharField(blank=True, max_length=120)),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['destinatario', 'leida'], name='pedidos_avi_destina_e5675b_idx')],
            },
        ),
    ]
