# Generated by Django 5.2.16 on 2026-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='courier',
            field=models.CharField(blank=True, choices=[('CHIBRA', 'Chibra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skucourier',
            name='courier',
            field=models.CharField(choices=[('CHIBRA', 'Chibra')], max_length=120),
        ),
        migrations.AlterField(
            model_name='skucourier',
            name='sku',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
