# Generated by Django 5.2.16 on 2026-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedido_courier_alter_skucourier_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='servicio_courier_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicio_courier_nombre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='skucourier',
            name='servicio_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='skucourier',
            name='servicio_nombre',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
