# Generated by Django 5.2.16 on 2026-07-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_servicio_courier_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tomado_en', models.DateTimeField(auto_now=True)),
                ('pid', models.IntegerField()),
            ],
        ),
    ]
