# Generated by Django 5.2.16 on 2026-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_locktarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='courier',
            field=models.CharField(blank=True, choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skucourier',
            name='courier',
            field=models.CharField(choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP')], max_length=120),
        ),
    ]
