# Generated by Django 5.2.16 on 2026-08-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_pedido_courier_alter_skucourier_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='courier',
            field=models.CharField(blank=True, choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP'), ('CYS', 'C&S'), ('BIOQUIMICACL', 'Bioquimica.cl'), ('STARKEN', 'Starken')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skucourier',
            name='courier',
            field=models.CharField(choices=[('CHIBRA', 'Chibra'), ('MOVEUP', 'MoveUP'), ('CYS', 'C&S'), ('BIOQUIMICACL', 'Bioquimica.cl'), ('STARKEN', 'Starken')], max_length=120),
        ),
    ]
