"""
Django settings for gestorBQ project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
#Llamar a dotenv para leer el .env
from dotenv import load_dotenv

#inicializar dotenv
load_dotenv()

#Llamar parametros de DB
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_PORT = os.getenv('DB_PORT')
DB_HOST = os.getenv('DB_HOST')

#Llamar parametros de Google OAuth
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')

#Llamar parametros de Token-SAP-BQ y URL de SAP
TOKEN_SAP_BQ_URL = os.getenv('TOKEN_SAP_BQ_URL')
TOKEN_SAP_BQ_USER = os.getenv('TOKEN_SAP_BQ_USER')
TOKEN_SAP_BQ_PASS = os.getenv('TOKEN_SAP_BQ_PASS')
SAP_URL = os.getenv('SAP_URL')

#Llamar al N° parametrizado de Ejecutivo web en SAP (Se puede cambiar en caso de que cambie algo en SAP, por eso SIEMPRE llamarlo desde aquí)
EJECUTIVO_WEB_SAP = int(os.getenv("EJECUTIVO_WEB_SAP", "25"))

#Llamar parametros de WooCommerce
WOO_BASE_URL = os.getenv('WOO_BASE_URL')
WOO_CONSUMER_KEY = os.getenv('WOO_CONSUMER_KEY')
WOO_CONSUMER_SECRET = os.getenv('WOO_CONSUMER_SECRET')

#Llamar parametros de Chibra
CHIBRA_BASE_URL = os.getenv("CHIBRA_BASE_URL")
CHIBRA_USER = os.getenv("CHIBRA_USER")
CHIBRA_PASSWORD = os.getenv("CHIBRA_PASSWORD")
CHIBRA_CLIENTE_REMITENTE = os.getenv("CHIBRA_CLIENTE_REMITENTE")

#Llamar parametros de MoveUP
MOVEUP_BASE_URL = os.getenv("MOVEUP_BASE_URL")
MOVEUP_ACCESS_TOKEN = os.getenv("MOVEUP_ACCESS_TOKEN")

#Parámetros de cuenta no-reply
EMAIL_SENDER = os.getenv("EMAIL_SENDER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_BCC = os.getenv("EMAIL_BCC", "informatica@bioquimica.cl,despachos@bioquimica.cl")
EMAIL_PROMO_ACTIVA = os.getenv("EMAIL_PROMO_ACTIVA", "False").strip().upper() == "TRUE"
EMAIL_PICKUP_PROMO_IMG_URL = os.getenv("EMAIL_PICKUP_PROMO_IMG_URL")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#Base de datos a utilizar
DATABASE_VERSION = os.getenv('DATABASE_VERSION')

#Configuración del cron
INTERVALO_SYNC_PEDIDOS = int(os.getenv('INTERVALO_SYNC_PEDIDOS', '10'))
CRON_SAP_ACTIVO = os.getenv('CRON_SAP_ACTIVO', 'True').strip().lower() == 'true'
CRON_WOO_ACTIVO = os.getenv('CRON_WOO_ACTIVO', 'True').strip().lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG', 'False').strip().lower() == 'true'

#Lista separada por comas (mismo criterio que EMAIL_BCC) — en prod: el hostname real (gestor.bioquimica.cl).
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()]

#Django exige el origen completo (con esquema) para aceptar POSTs — vacío en dev (mismo origen,
#sin proxy HTTPS de por medio); en prod: https://gestor.bioquimica.cl
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

#Solo tienen sentido con HTTPS real de por medio (Caddy/Cloudflare) — en dev (DEBUG=True, sin proxy)
#romperían el login, por eso quedan atrás de este gate en vez de fijos.
if not DEBUG:
    #Caddy termina el TLS antes de llegar a Django (Caddy→gunicorn es HTTP plano) — sin esto Django
    #cree que todo es HTTP y nunca manda las cookies Secure. Necesita que Caddy mande este header
    #(header_up X-Forwarded-Proto {scheme}, ya en el Caddyfile del runbook).
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!




SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'hd': 'bioquimica.cl'}, #Filtro para cuentas de bq
    }
}

SOCIALACCOUNT_ONLY = True

SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_ADAPTER = "cuentas.adapters.BioquimicaSocialAccountAdapter"

ACCOUNT_EMAIL_VERIFICATION = 'none'

#El link "Salir" del header es un <a> con GET; sin esto, allauth muestra antes una
#pantalla de confirmación ("¿Seguro que quieres salir?") en vez de cerrar sesión directo.
ACCOUNT_LOGOUT_ON_GET = True

LOGIN_REDIRECT_URL = '/cuentas/inicio/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cuentas',
    'ejecutivos',
    'pedidos',
    'pedidosRechazados',
    'envios',
    'cotizaciones',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  #sirve estáticos sin depender de cómo esté armado Caddy
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
      'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'gestorBQ.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pedidos.context_processors.datos_referencia',
            ],
        },
    },
]




WSGI_APPLICATION = 'gestorBQ.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DATABASE_VERSION == "SQLITE":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                  'timeout': 60,                                    # espera 30s el lock, no 5
                  'init_command': 'PRAGMA journal_mode=WAL;',       # lectores concurrentes durante escritura
                  'transaction_mode': 'IMMEDIATE',
              },
        }
    }
    
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,      # IP del server Postgres remoto
            'PORT': DB_PORT,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

#Sin esto, los logger.info(...) de la app (ej. pedidos.scheduler) se pierden en silencio —
#Django solo cablea handlers para sus propios loggers ("django.*"), no para los del proyecto.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "pedidos": {"handlers": ["console"], "level": "INFO"},
        #Sin esto, un 500 real (excepción no manejada) no deja ningún rastro en "docker compose
        #logs" — Django por defecto solo lo manda a mail_admins (necesita ADMINS + email
        #configurados, que no tenemos), nunca a consola.
        "django": {"handlers": ["console"], "level": "ERROR"},
        #TEMPORAL: diagnóstico del login Google en gestor-test (2026-07-29) — allauth atrapa el
        #OAuth2Error/RequestException del intercambio de token y muestra su propia pantalla de
        #error sin loguear nada, así que sin esto el traceback real queda invisible. Sacar cuando
        #se resuelva.
        "allauth": {"handlers": ["console"], "level": "DEBUG"},
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

#Destino de "collectstatic" — distinto de STATICFILES_DIRS a propósito (Django lo exige).
#En Docker: se genera al construir la imagen (ver Dockerfile), Whitenoise lo sirve directo.
STATIC_ROOT = BASE_DIR / "staticfiles"

if not DEBUG:
    #El storage con manifest (hash en el nombre + cache larga) exige que collectstatic ya haya
    #corrido — en dev nunca corre, por eso queda atrás de este gate (igual que SECURE_* arriba).
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
