# Generated by Django 5.2.16 on 2026-07-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ve_todas_cotizaciones',
            field=models.BooleanField(default=False, help_text='Supervisor comercial: ve las cotizaciones de todos los ejecutivos.'),
        ),
    ]
