# Generated by Django 5.2.16 on 2026-07-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_perfilusuario_ve_todas_cotizaciones'),
        ('ejecutivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ejecutivos',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='ejecutivos.ejecutivo'),
        ),
    ]
