# Generated by Django 5.2.16 on 2026-07-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejecutivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docentry', models.IntegerField(unique=True)),
                ('docnum', models.CharField(max_length=40, unique=True)),
                ('card_code', models.CharField(max_length=60)),
                ('rut', models.CharField(blank=True, max_length=40)),
                ('card_name', models.CharField(blank=True, max_length=400)),
                ('nombre_contacto', models.CharField(blank=True, max_length=400)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tipo_venta', models.CharField(blank=True, max_length=40)),
                ('area_trabajo', models.CharField(blank=True, max_length=40)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fecha_contabilizacion', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('actualizado_sap', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FACTURA_PARCIAL', 'Factura parcial'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('doc_status', models.CharField(blank=True, max_length=20)),
                ('cancelado', models.BooleanField(default=False)),
                ('lineas', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('ejecutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejecutivos.ejecutivo')),
            ],
            options={
                'ordering': ['-docentry'],
                'indexes': [models.Index(fields=['docnum'], name='cotizacione_docnum_1fd63c_idx'), models.Index(fields=['ejecutivo'], name='cotizacione_ejecuti_fbae3a_idx'), models.Index(fields=['estado'], name='cotizacione_estado_468b01_idx'), models.Index(fields=['fecha_caducidad'], name='cotizacione_fecha_c_21e151_idx')],
            },
        ),
    ]
