# Generated by Django 5.2.16 on 2026-07-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='ABIERTO', max_length=20),
        ),
    ]
