# Generated by Django 5.2.16 on 2026-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='total_facturado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('PARCIAL', 'Parcial'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], default='ABIERTO', max_length=20),
        ),
    ]
