# Generated by Django 5.2.16 on 2026-07-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosRechazados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorechazado',
            name='origen',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
